### PR TITLE
Remove content

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by matzew** [comment]
:+1:

**Comment by matzew** [comment]
merged! the 2.0.0 release is now available on maven cnetral

**Comment by matzew** [comment]
:tada:

**Comment by matzew** [comment]
I have also disabled the TravisCI hook for this repo

**Comment by danielpassos** [comment]
@matzew Thanks!

**Comment by matzew** [comment]
@danielpassos :kissing_heart:

**Pull request merged**
